variables:
  NIX_IMAGE: nixpkgs/nix-flakes@sha256:95bce4317c15dfab3babac5a6d19d3ed41e31a02a8aaf3d4f6639778cb763b0a

test:
  image: $NIX_IMAGE
  script:
    - nix develop -j auto -c clj -T:build test-clj
    - nix develop -j auto .#testWeb -c clj -T:build test-cljs
