image: nixpkgs/nix-flakes@sha256:95bce4317c15dfab3babac5a6d19d3ed41e31a02a8aaf3d4f6639778cb763b0a

build:
  script:
    - cd app/wisen
    - nix develop -c bash -c "clj -T:build uber"

test-frontend:
  script:
    - cd app/wisen
    - nix develop .#testWeb -c bash -c "clj -T:build karma"
