image: nixpkgs/nix-flakes@sha256:95bce4317c15dfab3babac5a6d19d3ed41e31a02a8aaf3d4f6639778cb763b0a

build:
  script:
    - cd ./wisen
    - nix develop -c clj -T:build uber
  artifacts:
    paths:
    - ./wisen/target/uber/*-standalone.jar
    - ./wisen/public/schema/schemaorg.jsonld
    - ./wisen/src/main/datashapesorg.ttl

test-frontend:
  script:
    - cd ./wisen
    - nix develop .#testWeb -c clj -T:build test-cljs

test-backend:
  script:
    - cd ./wisen
    - nix develop -c bash -c "clj -T:build test-clj"

deploy:
  image: debian@sha256:a726325fb0180a84cf1cb540df42959f413bf190aa2e6090d111222f3ddf8a06
  variables:
    GIT_STRATEGY: none
  before_script:
    - apt-get update && apt-get install -y ssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "$SP_EU_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SP_EU_SSH_SERVER_HOSTKEY" >> ~/.ssh/known_hosts
    - scp ./wisen/target/uber/*-standalone.jar root@sp-eu.ci.active-group.de:/root/wisen/app.jar
    - scp ./wisen/public/schema/schemaorg.jsonld root@sp-eu.ci.active-group.de:/root/wisen/public/schema/schemaorg.jsonld
    - scp ./wisen/src/main/datashapesorg.ttl root@sp-eu.ci.active-group.de:/root/wisen/datashapesorg.ttl
    - ssh root@sp-eu.ci.active-group.de 'systemctl restart sp-eu.service'
  needs:
    - build
    - test-frontend
    - test-backend
  dependencies:
    - build
