version: "0.5"

processes:
  shadow-cljs:
    command: clj -T:build cljs-watch
  frontend-test:
    command: clj -T:build cljs-watch-test
  backend:
    command: clj -M:backend -m wisen.backend.main
  ollama-server:
    command: ollama serve
  keycloak:
    command: >
      docker run -p 8080:8080
      -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      -v $(pwd)/keycloak:/opt/keycloak/data/import
      quay.io/keycloak/keycloak:latest
      start-dev --import-realm
    shell: true
