name: SP-EU deployment
on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: [ "ubuntu-24.04" ]
    name: test
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - name: backend tests
        run: nix develop -j auto -c bash -c "cd wisen && clj -T:build test-clj"
      - name: client tests
        run: nix develop -j auto .#testWeb -c bash -c "cd wisen && clj -T:build test-cljs"

  integration-test:
    runs-on: [ "ubuntu-24.04" ]
    name: integration-test
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - run: nix build .#integration-test -L

  deploy:
    runs-on: [ "ubuntu-24.04" ]
    if: github.ref == 'refs/heads/main'
    needs: [ test ]
    name: deploy NixOS generation
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - name: nixos-rebuild
        run: |
          mkdir -m 700 -p ~/.ssh
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SP_EU_HOST_KEY }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SP_EU_SSH_KEY }}" | tr -d '\r' | ssh-add - >/dev/null
          nix shell nixpkgs#nixos-rebuild -c \
              nixos-rebuild switch -j auto --flake .#prod-x86_64-linux \
              --target-host root@sp-eu.ci.active-group.de
          ssh root@sp-eu.ci.active-group.de systemctl restart sp-eu.service
